NumPy 배열 공부

In [1]:
import numpy as np

In [4]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

In [ ]:
# 배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산 지원


In [7]:
# 리스트 객체로 연산할 경우
data = [0,1,2,3,4,5,6,7,8,9]

answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
# 벡터화 연산 사용할 경우
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# 참고 : 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼 증가
L = [0,1,2,3,4]
print( L * 2)

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [12]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2*a + b

array([12, 24, 36])

In [13]:
a == 2

array([False,  True, False])

In [14]:
b > 10

array([False,  True,  True])

In [15]:
(a == 2) & (b > 10)

array([False,  True, False])

In [ ]:
# 2차원 배열 만들기
# ndarray는 N-dimensional Array의 약자
# 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원원

In [17]:
# 2 x 3 배열 생성
c = np.array([[0,1,2], [3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
# 행의 개수
len(c)

2

In [19]:
# 열의 개수
len(c[0])

3

In [20]:
example = np.array([[10,20,30,40], [50,60,70,80]])
example

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [21]:
# 3차원 배열 만들기
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [22]:
len(d), len(d[0]), len(d[0][0])


(2, 3, 4)

In [23]:
# ndim 속성은 배열의 차원, shape 속성은 배열의 크기를 반환

a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [24]:
c = np.array([[0,1,2], [3,4,5]])
print(c.ndim)
print(c.shape)


2
(2, 3)


In [25]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [26]:
# 일차원 배열의 인덱싱은 리스트의 인덱싱과 같다.
a = np.array([0,1,2,3,4])
a[2]

2

In [27]:
a[-1]

4

In [28]:
a = np.array([[0,1,2], [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
print(a[0,0])
print(a[0,1])
print(a[-1,-1])

0
1
5


In [30]:
# 배열 슬라이싱(slicing)
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
a[0,:]

array([0, 1, 2, 3])

In [32]:
a[:,1]

array([1, 5])

In [33]:
a[1,1:]

array([5, 6, 7])

In [34]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [36]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
m[1,2]

7

In [40]:
m[-1,-1]

14

In [41]:
m[1,1:3]

array([6, 7])

In [42]:
m[1:, 2]

array([ 7, 12])

In [43]:
m[0:2, 3:]

array([[3, 4],
       [8, 9]])

In [44]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
# idx는 인덱스 배열
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [45]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [46]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [47]:
a[a % 2 ==0]

array([0, 2, 4, 6, 8])

In [48]:
# 정수 배열 인덱싱에서는 인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수이여야 한다.

a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
a[idx]


array([11, 33, 55, 77, 99])

In [49]:
idx = np.array([0,0,0,0,0,0,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 33, 33, 33, 33, 33])

In [50]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a[:, [True ,False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [52]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [54]:
x = np.array([1,2,3,4,5,6,7,8,9,10,
              11,12,13,14,15,16,17,18,19,20])
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [58]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [59]:
x[(x % 3 ==0) & (x % 4 ==1)]

array([9])