NumPy_2

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])
x.dtype

dtype('int64')

In [4]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [5]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [10]:
x = np.array([1,2,3], dtype='f')
x


array([1., 2., 3.], dtype=float32)

In [12]:
x[0]+x[1]

3.0

In [13]:
x = np.array([1,2,3], dtype='U')
x

array(['1', '2', '3'], dtype='<U1')

In [17]:
x[0]+x[1]+x[2]

'123'

In [ ]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

In [19]:
np.log(0)

<ipython-input-19-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [22]:
np.exp(-np.inf)

0.0

In [23]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [24]:
b = np.zeros((2,3))
b


array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
c = np.zeros((5,2), dtype="i")
c


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [26]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [27]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d
# 더 큰 크기의 문자열을 할당하면 잘림림

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [28]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [29]:
# 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶을 때
# ones_like, zeros_like

f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
# empty 명령 -> 배열을 생성만 하고 특정한 값으로 초기화 x
# empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로
# 배열의 원소의 값을 미리 알 수 없다.

In [30]:
g = np.empty((4,3))
g

array([[2.3745032e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [31]:
# arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수
# 만큼 분할한다.

In [34]:
np.linspace(0,100,5)


array([  0.,  25.,  50.,  75., 100.])

In [35]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [36]:
# 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업

A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [41]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [44]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
# 다차원 배열을 무조건 1차원으로 만들기 위해서는 flatten나 ravel 메서드를 사용용

In [45]:
a.flatten()

array([1, 2, 3, 4])

In [47]:
a.ravel()

array([1, 2, 3, 4])

In [48]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [49]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [50]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 위 3개 배열 모두 다른 객체

In [51]:
x

array([0, 1, 2, 3, 4])

In [54]:
x[:, np.newaxis]
x.shape

(5,)

In [55]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [57]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [58]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])