In [ ]:
# 난수(random number)를 발생시키는 방법
# 주로 NumPy의 random 서브패키지에서 제공

In [ ]:
# seed를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열 생성

In [2]:
import numpy as np

In [ ]:
np.random.seed(0) # 인수는 0과 같거나 큰 정수

In [ ]:
# rand 함수는 0과 1 사이의 난수를 발생시키는 함수
# 인수로 받은 숫자 횟수만큼 난수를 발생시킴

In [ ]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [ ]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [ ]:
# 시드를 0으로 재설정하고 다시 난수를 발생시키기

In [ ]:
np.random.seed(0)

In [ ]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [ ]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [ ]:
# 데이터의 순서를 바꾸려면 shuffle 함수를 사용

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [ ]:
# 데이터 샘플링
# 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 혹은 샘플링
# choice 함수 사용

In [ ]:
np.random.seed(0)

In [ ]:
np.random.choice(5,5,replace=False)

array([2, 0, 1, 3, 4])

In [ ]:
np.random.choice(5,3,replace=False)

array([0, 2, 1])

In [ ]:
np.random.choice(5,10)

array([2, 4, 0, 0, 4, 2, 1, 0, 1, 1])

In [ ]:
np.random.choice(5,10, p=[0.1, 0, 0.3, 0.6, 0])

array([0, 0, 0, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
 # 난수 생성
 # rand : 0부터 1사이의 균일 분포
 # randn : 표준 정규 분포
 # randint : 균일 분포의 정수 난수

In [ ]:
# rand 함수는 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성
# 숫자 인수는 생성할 난수의 크기
# 여러개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [3]:
np.random.rand(10)

array([0.4195347 , 0.46871033, 0.86243633, 0.55807001, 0.11328012,
       0.40689346, 0.22563574, 0.40424094, 0.57107827, 0.47027157])

In [4]:
np.random.rand(3,5)

array([[0.39705857, 0.00892019, 0.9858621 , 0.08479984, 0.33032506],
       [0.14228523, 0.50821059, 0.97860554, 0.76244858, 0.25326735],
       [0.05941641, 0.74906308, 0.1540913 , 0.28432698, 0.50443193]])

In [ ]:
# randn 함수는 기댓값이 0이고 표준편차가 1인
# 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [5]:
np.random.randn(10)

array([ 0.05121573, -0.71988288,  1.09931615,  0.15937583, -0.73903424,
       -0.43801082, -1.01396341, -0.63212124,  1.09335676, -0.43873582])

In [6]:
np.random.randn(3,5)

array([[ 0.53224256, -0.7171401 , -0.73841858,  1.32067766, -0.02891081],
       [ 0.57689344, -0.26748474, -0.41606098,  0.44789774, -0.68433663],
       [-1.30123574,  0.76272849,  0.28527608,  0.15471052,  2.34235167]])

In [7]:
np.random.randint(10, size = 10)

array([9, 0, 0, 6, 8, 4, 0, 0, 1, 6])

In [8]:
np.random.randint(10,20,size=10)

array([17, 18, 11, 12, 13, 15, 19, 18, 10, 14])

In [10]:
np.random.randint(10, 20, size=(3,5))

array([[19, 16, 16, 12, 12],
       [10, 10, 19, 19, 12],
       [12, 16, 11, 15, 14]])

In [ ]:
# 정수 데이터 카운팅

In [19]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [20]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [21]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [22]:
count

array([2, 2, 1])

In [26]:
np.bincount([1,1,2,2,2,3], minlength=6)

array([0, 2, 3, 1, 0, 0])