youtube_1

In [ ]:
# list vs array
# array : 적은 메모리로 데이터를 빠르게 처리하고 모든 원소는 같은 자료형을 가진다
# list : 상대적으로 속도가 매우 느리고 원소가 각각 다른 자료형을 가질 수 있다.

In [ ]:
# ndarray
# N-dimensional Array
# 데이터 타입은 모두 동일함
# 내부반복문을 사용함으로써 속도가 빠르다
# 배열간에 산술 연산이 가능함

In [ ]:
# dtype : 자료형 확인
# astype : 자료형 변경
# np.arange(start,stop,step) : step에 따라 증가하는 수열 생성
# reshape : 만들어진 배열의 데이터를 그대로 가지고 형태를 바꿈

In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a
print(a)

[1 2 3]


In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = ['1','2','3']
b = np.array(a, dtype=int)
b

In [4]:
b.dtype

dtype('int64')

In [ ]:
data = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [ ]:
y = np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y[0,0]

1

In [ ]:
x1 = np.arange(1,9).reshape(2,4)
x1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
x2 = np.arange(1,9).reshape(4,2)
x2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
x3 = np.arange(1,13).reshape(3,2,2) # 3덩어리 2행 2열
x3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [11]:
x3[2,1,1]

12

In [ ]:
# 반복문을 사용하지 않아도 배열의 모든 원소는 반복 연산이 사용됨


In [ ]:
a = np.array([1,2,3])
b = 3
print(a+b)
print(a-b)

[4 5 6]
[-2 -1  0]


In [ ]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
np.dot(data,data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# 차원
# 0차원 : scalar(하나의 데이터 값으로만 존재)
# 1차원 : Vector(숫자들의 배열)
# 2차원 : Matrix(행(array), 열(columns))
# 3차원이상 : Tensor(다차원배열)


In [ ]:
a = np.array(1) # 0차원
a
print(a)
print(a.shape)
print(a.ndim)

1
()
0


In [ ]:
a = np.array([1]) # 1차원

print(a)
print(a.shape)
print(a.ndim)

[1]
(1,)
1


In [12]:
a = np.array([1,2,1,2,1])

print(a)
print(a.shape)
print(a.ndim)

[1 2 1 2 1]
(5,)
1


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [ ]:
# Tensor(다차원배열)

In [ ]:
a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(a)
print(a.shape)
print(a.ndim)
# 2덩어리 3행 2열

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [ ]:
# 통계함수
# sum, mean, max, min, std(표준편차), var(분산)

In [19]:
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
x = np.sum(a)
print(x)

45


In [21]:
x = np.mean(a)
print(x)

4.5


In [22]:
a[0][0] = 10
print(a)

[[10  1  2  3  4]
 [ 5  6  7  8  9]]


In [30]:
# 실전 문제

import numpy as np
점수 = np.array([80,88,90,95])
단위 = np.array([3,2,1,4])
print(점수*단위)
총점 = sum(점수*단위)
평균 = 총점/sum(단위)
print('총점은:' ,총점, '평균은:' ,평균)
print('총점은: {}, 평균은: {}'.format(총점, 평균))

[240 176  90 380]
총점은: 886 평균은: 88.6
총점은: 886, 평균은: 88.6


In [26]:
점수 = np.array([80,88,90,95])
평균 = np.mean(점수)
print(평균)

88.25


In [32]:
import numpy as np
Kcal = np.array([90,130,100,360])
total = np.sum(Kcal)
ave = np.mean(Kcal)
H_K = max(Kcal)
L_K = min(Kcal)
print('총 Kcal:' , total)
print('평균 Kcal:' , ave)
print('가장높은 Kcal:', H_K)
print('가장낮은 Kcal:', L_K)

총 Kcal: 680
평균 Kcal: 170.0
가장높은 Kcal: 360
가장낮은 Kcal: 90


In [38]:
import numpy as np
국어 = np.array([88,95,70])
영어 = np.array([90,80,90])
수학 = np.array([65,75,55])

print('국어총점:{}, 영어총점:{}, 수학총점:{}'.format(np.sum(국어), np.sum(영어), np.sum(수학)))
print('국어평균:' ,np.mean(국어), '영어평균:' ,np.mean(영어), '수학평균:' ,np.mean(수학))
print(max(국총,수총, 영총))
print(min(국총, 수총, 영총))

국어총점:253, 영어총점:260, 수학총점:195
국어평균: 84.33333333333333 영어평균: 86.66666666666667 수학평균: 65.0
260
195


In [39]:
round(3.1415926535,2)

3.14

In [40]:
num = 1.415926535
print('소수두자리에서 반올림: {:.2f}'.format(3.1415926535))
print('또다른 반올림: {:.2f}'.format(num))

소수두자리에서 반올림: 3.14
또다른 반올림: 1.42


In [41]:
num = 1.415926535
print(f'소수두자리에서 반올림: {3.1415926535:.2f}')
print(f'또다른 반올림: {num:.2f}')

소수두자리에서 반올림: 3.14
또다른 반올림: 1.42
